# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

import gzip
import json
import os
import utils

METADATA_HEADER = """#pragma once

#include "common.h"

// DO NOT EDIT THIS FILE DIRECTLY
// This file is automatically generated from keyboard.json.

// Compressed metadata for the web configurator
static const uint8_t metadata_compressed[] = {};
"""

Import("env")

keyboard = env["PIOENV"]

kb_json = utils.get_kb_json(keyboard)
driver_json = utils.get_driver_json(keyboard)

metadata = {
    "name": kb_json["name"],
    "vendorId": kb_json["usb"]["vid"],
    "productId": kb_json["usb"]["pid"],
    "usbHighSpeed": kb_json["usb"]["port"] == "hs",
    "adcResolution": utils.get_adc_resolution(kb_json, driver_json),
    "numProfiles": kb_json["keyboard"]["num_profiles"],
    "numLayers": kb_json["keyboard"]["num_layers"],
    "numKeys": kb_json["keyboard"]["num_keys"],
    "numAdvancedKeys": kb_json["keyboard"]["num_advanced_keys"],
    "layout": kb_json["layout"],
    "defaultKeymap": kb_json["keymap"],
}

if "profile_keymaps" in kb_json:
    base_keymap = [list(layer) for layer in kb_json["keymap"]]
    num_profiles = kb_json["keyboard"]["num_profiles"]
    num_layers = kb_json["keyboard"]["num_layers"]
    raw_profile_keymaps = kb_json["profile_keymaps"]

    if len(raw_profile_keymaps) > num_profiles:
        raise ValueError("profile_keymaps must not have more entries than num_profiles")

    resolved_profile_keymaps = []
    for i in range(num_profiles):
        if i < len(raw_profile_keymaps) and raw_profile_keymaps[i]:
            profile_keymap = raw_profile_keymaps[i]
            if len(profile_keymap) != num_layers:
                raise ValueError(
                    f"profile_keymaps[{i}] must have {num_layers} layers"
                )
            resolved_profile_keymaps.append([list(layer) for layer in profile_keymap])
        else:
            resolved_profile_keymaps.append([list(layer) for layer in base_keymap])

    metadata["defaultProfileKeymaps"] = resolved_profile_keymaps

uncompressed = json.dumps(metadata).encode("utf-8")
compressed = gzip.compress(uncompressed)

print(f"Uncompressed metadata size: {len(uncompressed)} bytes")
print(f"Compressed metadata size: {len(compressed)} bytes")
print(json.dumps(metadata, indent=2))

with open(os.path.join("include", "metadata.h"), "w") as f:
    f.write(METADATA_HEADER.format(utils.to_c_array(compressed)))
